volumes:
  postgres:
  synapse-data:
services:
  postgres:
    image: docker.io/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - /Users/dineshdb/src/github.com/dineshdb/matrix-playground/server/sql-init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  # enable this if you don't have traefik already setup
  traefik:
    image: docker.io/traefik:latest
    privileged: true
    command:
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
    ports:
      - 80:80
  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    user: "991:991"
    environment:
      - SYNAPSE_CONFIG_PATH=/config/homeserver.yaml
    depends_on:
      - postgres
      - oidc
    labels:
      - traefik.http.routers.synapse.rule=Host(`synapse.localhost`)
      - traefik.http.services.synapse.loadbalancer.server.port=8008
    volumes:
      - synapse-data:/data:z
      - /Users/dineshdb/src/github.com/dineshdb/matrix-playground/server/homeserver.yaml:/config/homeserver.yaml
      - /Users/dineshdb/src/github.com/dineshdb/matrix-playground/server/matrix.localdomain.log.config:/config/matrix.localdomain.log.config
      - /Users/dineshdb/src/github.com/dineshdb/matrix-playground/server/matrix.localdomain.signing.key:/config/matrix.localdomain.signing.key
  redis:
    image: docker.io/redis
    ports:
      - 6379:6379
  oidc:
    build: oidc-companion
    environment:
      - PORT=3000
      - ADMIN_USERNAME=admin
      - HOMESERVER_URL=http://synapse:8008
    labels:
      - traefik.http.routers.auth.rule=Host(`auth.matrix.localdomain`)
      - traefik.http.services.auth.loadbalancer.server.port=3000
  # bot:
  #   image: docker.io/denoland/deno:1.38.0
  #   working_dir: /app
  #   user: "deno:deno"
  #   command:
  #     - deno
  #     - run
  #     - -A
  #     - --watch
  #     - --unstable
  #     - bot.ts
  #   volumes:
  #     - /Users/dineshdb/src/github.com/dineshdb/matrix-playground/app-server:/app
  #   environment:
  #     - MAS=http://mas:8080
  #     - HOMESERVER_URL=http://matrix.localdomain
  matrix:
    build:
      context: ./matrix-proxy
    depends_on:
      - synapse
      - oidc
    labels:
      - traefik.http.routers.matrix.rule=Host(`matrix.localdomain`)
      - traefik.http.services.matrix.loadbalancer.server.port=80
