CREATE USER mas WITH PASSWORD 'password';
CREATE DATABASE mas;
GRANT ALL PRIVILEGES ON DATABASE mas TO mas;
ALTER DATABASE mas OWNER TO mas;

CREATE USER synapse WITH PASSWORD 'password';
CREATE DATABASE synapse TEMPLATE='template0' LC_COLLATE='C' LC_CTYPE='C';
GRANT ALL PRIVILEGES ON DATABASE synapse TO synapse;
ALTER DATABASE synapse OWNER TO synapse;
